name: instachatty
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  page_view_indicators: ^1.3.1
  shared_preferences: ^0.5.6
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  flutter_svg: ^0.19.0
  image_picker: ^0.6.5
  firebase_storage: ^3.1.5
  progress_dialog: ^1.2.2
  provider: ^4.0.1
  url_launcher: ^5.4.11
  curved_navigation_bar: ^0.3.1
  carousel_pro: ^1.0.0
  intl: ^0.16.1
  image_editor_pro: ^1.0.5
  cached_network_image: ^2.1.0+1
  uuid: ^2.1.0
  flutter_typeahead: ^1.9.2
  video_thumbnail: ^0.2.1
  path_provider: ^1.6.11
  photo_view: ^0.10.2
  video_player: ^0.11.0
  flutter_facebook_login: ^3.0.0
  http: ^0.12.1
  flutter_webrtc: ^0.3.3
  flutter_ringtone_player: ^2.0.0
  wakelock: ^0.2.0+1
  firebase_messaging: ^6.0.16
  audio_recorder: ^1.0.2
  audioplayers: ^0.16.1
  permission_handler: ^5.0.1+1
  intl_phone_number_input: ^0.5.2+2
  pin_code_fields: ^5.2.0
  callkeep: ^0.1.1
  easy_localization: ^2.3.3
  google_nav_bar: ^3.1.0
  line_icons: ^0.2.0
  badges: ^1.1.6
  flutter_google_places: ^0.2.4
  google_maps_webservice: ^0.0.16
  filter_list: ^0.0.5
  easy_popup: ^1.0.0
  geocoder: ^0.2.1
  geodesy: ^0.3.2
  country_state_city_picker: ^1.2.4
  flutter_luban: ^0.1.11
  multi_image_picker: ^4.7.14
  photofilters: ^2.0.1

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto.ttf

    - family: sanFran
      fonts:
        - asset: fonts/SF-Pro-Display-Semibold.otf

    - family: Bauhaus93
      fonts:
        - asset: fonts/Bauhaus93.ttf